package jp.co.fullness.ddd.infrastructure.category;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * product_category テーブルにマッピングする JPA エンティティ（永続化モデル）。
 *
 * <p>ドメインの {@code Category} とは別物で、JPA/Hibernate に依存するのはこの層まで。
 * ドメインへの変換は {@code CategoryEntityMapper}（MapStruct）が担う。</p>
 */
@Getter
@Setter
@Entity
@Table(name = "product_category")
public class CategoryEntity {

    /** 主キー（GENERATED BY DEFAULT AS IDENTITY） */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /** 識別Id（category_uuid, VARCHAR(36)） */
    @Column(name = "category_uuid", nullable = false, unique = true, length = 36)
    private String categoryUuid;

    /** カテゴリ名 */
    @Column(name = "name", nullable = false, unique = true, length = 20)
    private String name;
}